application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true

logging:
  level: INFO
  format: json

# Development configuration (enabled via environment variable)
development:
  enabled: false
  port: 3000
  hot_reload: false
  debug_mode: false
  mock_apis: false

# Experimental Application Configuration
experimental:
  enabled: false
  application:
    version: 3.0.0-experimental
    environment: testing
  server:
    ports: [9000, 9001, 9002]
  logging:
    level: TRACE
    format: structured
    output: /var/log/experimental.log
    ai_analysis: false
  database:
    host: cluster.example.com
    port: 5432
    name: devops_experimental
    distributed: true
  features:
    auto_scaling: advanced
    load_balancer: ai-optimized
    chaos_engineering: disabled
  ai_features:
    predictive_scaling: false
    anomaly_detection: false
    auto_optimization: false
    model_version: "v2.1.0"
  cloud_providers:
    - aws
    - azure
    - gcp
    - digitalocean
  security:
    zero_trust: disabled
    encryption: AES-256
    audit_logging: basic
  model_version: "v2.1.0"
